2020-04-07 23:02:23,197 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-07 23:03:16,478 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-07 23:03:43,839 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/favicon.ico'
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
2020-04-07 23:05:17,687 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         GET                            handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-07 23:05:17,689 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-07 23:05:17,690 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-07 23:05:17,693 [INFO ]  Enabling coroutine debugging. Loop id 2223042265992.
2020-04-07 23:05:17,982 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmpnf2t41cm'.
2020-04-07 23:05:18,476 [DEBUG]  Loading the model ...
2020-04-07 23:05:20,174 [DEBUG]  Finished loading the model.
2020-04-07 23:05:20,175 [DEBUG]  Building tensorflow prediction graph...
2020-04-07 23:05:24,521 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-07 23:05:24,523 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path 'C:\Users\ASUS\AppData\Local\Temp\tmpnf2t41cm\nlu' doesn't exist?
2020-04-07 23:05:24,532 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-07 23:05:24,533 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-07 23:05:24,819 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmp9ltq_o7d'.
2020-04-07 23:05:24,823 [DEBUG]  Using yaml library: c:\users\asus\miniconda3\envs\rasa\lib\site-packages\ruamel\yaml\__init__.py
2020-04-07 23:05:25,404 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-07 23:07:06,644 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-07 23:09:48,924 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/favicon.ico'
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
2020-04-07 23:10:40,733 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-07 23:11:10,216 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-07 23:11:35,071 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-07 23:12:05,629 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-07 23:12:35,473 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-07 23:13:29,519 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-07 23:14:39,991 [ERROR]  Exception occurred while handling uri: 'http://07e546b5.ngrok.io/parse?project=current&token='
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /parse not found
2020-04-08 12:32:18,019 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         OPTIONS                        handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-08 12:32:18,026 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-08 12:32:18,028 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-08 12:32:18,035 [INFO ]  Enabling coroutine debugging. Loop id 3012746273608.
2020-04-08 12:32:19,485 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmph525eg8y'.
2020-04-08 12:32:20,823 [DEBUG]  Loading the model ...
2020-04-08 12:32:23,450 [DEBUG]  Finished loading the model.
2020-04-08 12:32:23,453 [DEBUG]  Building tensorflow prediction graph...
2020-04-08 12:32:30,334 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-08 12:32:30,339 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path 'C:\Users\ASUS\AppData\Local\Temp\tmph525eg8y\nlu' doesn't exist?
2020-04-08 12:32:30,362 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-08 12:32:30,364 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-08 12:32:31,114 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmpv1ce0b7n'.
2020-04-08 12:32:31,121 [DEBUG]  Using yaml library: c:\users\asus\miniconda3\envs\rasa\lib\site-packages\ruamel\yaml\__init__.py
2020-04-08 12:32:31,345 [DEBUG]  Loading the model ...
2020-04-08 12:32:32,308 [DEBUG]  Finished loading the model.
2020-04-08 12:32:32,317 [DEBUG]  Building tensorflow prediction graph...
2020-04-08 12:32:33,667 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-08 12:32:33,680 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-08 12:32:43,160 [DEBUG]  Creating a new tracker for id 'healthchain'.
2020-04-08 12:32:43,163 [DEBUG]  Starting a new session for conversation ID 'healthchain'.
2020-04-08 12:32:43,165 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x000002BD02356648>, <rasa.core.events.ActionExecuted object at 0x000002BD02356AC8>]'.
2020-04-08 12:32:43,167 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: None
	name: None
	remedy: None
	requested_slot: None
	symptom: None
2020-04-08 12:32:44,062 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 12:32:44,066 [DEBUG]  Adding following selector key to message property: default
2020-04-08 12:32:44,070 [DEBUG]  Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.9737305641174316}' and entities '[]'
2020-04-08 12:32:44,073 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2020-04-08 12:32:44,079 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 12:32:44,082 [DEBUG]  There is no memorised next action
2020-04-08 12:32:44,089 [DEBUG]  There is no active form
2020-04-08 12:32:44,089 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:32:44,093 [DEBUG]  Predicted next action 'find_facility_types' with confidence 0.82.
2020-04-08 12:32:44,098 [DEBUG]  Calling action endpoint to run action 'find_facility_types'.
2020-04-08 12:32:46,241 [ERROR]  Encountered an exception while running action 'find_facility_types'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-08 12:32:46,247 [DEBUG]  Failed to execute custom action.
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\utils\endpoints.py", line 150, in request
    resp.status, resp.reason, await resp.content.read()
rasa.utils.endpoints.ClientResponseError: 404, Not Found, body='b'{"error":"No registered action found for name \'find_facility_types\'.","action_name":"find_facility_types"}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\processor.py", line 616, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 572, in run
    raise Exception("Failed to execute custom action.") from e
Exception: Failed to execute custom action.
2020-04-08 12:32:46,252 [DEBUG]  Action 'find_facility_types' ended with events '[]'.
2020-04-08 12:32:46,259 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: None
	name: None
	remedy: None
	requested_slot: None
	symptom: None
2020-04-08 12:32:46,264 [DEBUG]  Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}]
2020-04-08 12:32:46,265 [DEBUG]  There is a memorised next action 'action_listen'
2020-04-08 12:32:46,280 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2020-04-08 12:32:46,280 [DEBUG]  There is no active form
2020-04-08 12:32:46,287 [DEBUG]  Predicted next action using policy_0_MemoizationPolicy
2020-04-08 12:32:46,291 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-08 12:32:46,292 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 12:32:46,294 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 12:33:18,888 [DEBUG]  Recreating tracker for id 'healthchain'
2020-04-08 12:33:18,914 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 12:33:18,918 [DEBUG]  Adding following selector key to message property: default
2020-04-08 12:33:18,922 [DEBUG]  Received user message 'hey there' with intent '{'name': 'greet', 'confidence': 0.9814113974571228}' and entities '[]'
2020-04-08 12:33:18,929 [DEBUG]  Logged UserUtterance - tracker now has 7 events.
2020-04-08 12:33:18,933 [DEBUG]  Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 12:33:18,937 [DEBUG]  There is no memorised next action
2020-04-08 12:33:18,950 [DEBUG]  There is no active form
2020-04-08 12:33:18,955 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:33:18,959 [DEBUG]  Predicted next action 'find_facility_types' with confidence 0.76.
2020-04-08 12:33:18,964 [DEBUG]  Calling action endpoint to run action 'find_facility_types'.
2020-04-08 12:33:21,046 [ERROR]  Encountered an exception while running action 'find_facility_types'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-08 12:33:21,053 [DEBUG]  Failed to execute custom action.
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\utils\endpoints.py", line 150, in request
    resp.status, resp.reason, await resp.content.read()
rasa.utils.endpoints.ClientResponseError: 404, Not Found, body='b'{"error":"No registered action found for name \'find_facility_types\'.","action_name":"find_facility_types"}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\processor.py", line 616, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 572, in run
    raise Exception("Failed to execute custom action.") from e
Exception: Failed to execute custom action.
2020-04-08 12:33:21,062 [DEBUG]  Action 'find_facility_types' ended with events '[]'.
2020-04-08 12:33:21,065 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: None
	name: None
	remedy: None
	requested_slot: None
	symptom: None
2020-04-08 12:33:21,075 [DEBUG]  Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}]
2020-04-08 12:33:21,079 [DEBUG]  There is no memorised next action
2020-04-08 12:33:21,089 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2020-04-08 12:33:21,093 [DEBUG]  There is no active form
2020-04-08 12:33:21,097 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:33:21,100 [DEBUG]  Predicted next action 'action_listen' with confidence 0.85.
2020-04-08 12:33:21,107 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 12:33:21,114 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 12:33:27,306 [DEBUG]  Recreating tracker for id 'healthchain'
2020-04-08 12:33:27,320 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 12:33:27,320 [DEBUG]  Adding following selector key to message property: default
2020-04-08 12:33:27,324 [DEBUG]  Received user message 'new york' with intent '{'name': 'inform', 'confidence': 0.9931437969207764}' and entities '[{'entity': 'location', 'start': 4, 'end': 8, 'extractor': 'DIETClassifier', 'value': 'york'}]'
2020-04-08 12:33:27,327 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: york
	name: None
	remedy: None
	requested_slot: None
	symptom: None
2020-04-08 12:33:27,327 [DEBUG]  Logged UserUtterance - tracker now has 11 events.
2020-04-08 12:33:27,335 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}, {'intent_inform': 1.0, 'prev_action_listen': 1.0, 'entity_location': 1.0}]
2020-04-08 12:33:27,335 [DEBUG]  There is no memorised next action
2020-04-08 12:33:27,341 [DEBUG]  There is no active form
2020-04-08 12:33:27,345 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:33:27,350 [DEBUG]  Predicted next action 'find_healthcare_address' with confidence 0.46.
2020-04-08 12:33:27,354 [DEBUG]  Calling action endpoint to run action 'find_healthcare_address'.
2020-04-08 12:33:29,451 [ERROR]  Encountered an exception while running action 'find_healthcare_address'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-08 12:33:29,457 [DEBUG]  Failed to execute custom action.
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\utils\endpoints.py", line 150, in request
    resp.status, resp.reason, await resp.content.read()
rasa.utils.endpoints.ClientResponseError: 404, Not Found, body='b'{"error":"No registered action found for name \'find_healthcare_address\'.","action_name":"find_healthcare_address"}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\processor.py", line 616, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 572, in run
    raise Exception("Failed to execute custom action.") from e
Exception: Failed to execute custom action.
2020-04-08 12:33:29,469 [DEBUG]  Action 'find_healthcare_address' ended with events '[]'.
2020-04-08 12:33:29,471 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: york
	name: None
	remedy: None
	requested_slot: None
	symptom: None
2020-04-08 12:33:29,486 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_find_facility_types': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}, {'intent_inform': 1.0, 'prev_action_listen': 1.0, 'entity_location': 1.0}, {'intent_inform': 1.0, 'prev_find_healthcare_address': 1.0, 'entity_location': 1.0}]
2020-04-08 12:33:29,490 [DEBUG]  There is no memorised next action
2020-04-08 12:33:29,504 [DEBUG]  There is no mapped action for the predicted intent, 'inform'.
2020-04-08 12:33:29,508 [DEBUG]  There is no active form
2020-04-08 12:33:29,515 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:33:29,517 [DEBUG]  Predicted next action 'utter_address' with confidence 0.53.
2020-04-08 12:33:29,538 [DEBUG]  Action 'utter_address' ended with events '[BotUttered('The address is None.', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1586329409.5374806)]'.
2020-04-08 12:33:29,542 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_find_facility_types': 1.0}, {'intent_inform': 1.0, 'prev_action_listen': 1.0, 'entity_location': 1.0}, {'intent_inform': 1.0, 'prev_find_healthcare_address': 1.0, 'entity_location': 1.0}, {'intent_inform': 1.0, 'prev_utter_address': 1.0, 'entity_location': 1.0}]
2020-04-08 12:33:29,543 [DEBUG]  There is no memorised next action
2020-04-08 12:33:29,561 [DEBUG]  There is no mapped action for the predicted intent, 'inform'.
2020-04-08 12:33:29,566 [DEBUG]  There is no active form
2020-04-08 12:33:29,569 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:33:29,572 [DEBUG]  Predicted next action 'action_listen' with confidence 0.82.
2020-04-08 12:33:29,580 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 12:33:29,585 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 12:44:14,863 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         GET                            handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-08 12:44:14,865 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-08 12:44:14,869 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-08 12:44:14,872 [INFO ]  Enabling coroutine debugging. Loop id 2584697365192.
2020-04-08 12:44:15,689 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmpvhxwjt51'.
2020-04-08 12:44:16,944 [DEBUG]  Loading the model ...
2020-04-08 12:44:19,726 [DEBUG]  Finished loading the model.
2020-04-08 12:44:19,726 [DEBUG]  Building tensorflow prediction graph...
2020-04-08 12:44:31,372 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-08 12:44:31,377 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path 'C:\Users\ASUS\AppData\Local\Temp\tmpvhxwjt51\nlu' doesn't exist?
2020-04-08 12:44:31,399 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-08 12:44:31,401 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-08 12:44:32,224 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmp8g5wzhlo'.
2020-04-08 12:44:32,231 [DEBUG]  Using yaml library: c:\users\asus\miniconda3\envs\rasa\lib\site-packages\ruamel\yaml\__init__.py
2020-04-08 12:44:32,383 [DEBUG]  Loading the model ...
2020-04-08 12:44:33,283 [DEBUG]  Finished loading the model.
2020-04-08 12:44:33,296 [DEBUG]  Building tensorflow prediction graph...
2020-04-08 12:44:34,710 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-08 12:44:34,723 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-08 12:44:42,297 [DEBUG]  Creating a new tracker for id 'healthchain'.
2020-04-08 12:44:42,300 [DEBUG]  Starting a new session for conversation ID 'healthchain'.
2020-04-08 12:44:42,302 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x00000259D59C8748>, <rasa.core.events.ActionExecuted object at 0x00000259D59BEE08>]'.
2020-04-08 12:44:42,305 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: None
	name: None
	remedy: None
	symptom: None
2020-04-08 12:44:42,739 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 12:44:42,742 [DEBUG]  Adding following selector key to message property: default
2020-04-08 12:44:42,744 [DEBUG]  Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.9737305641174316}' and entities '[]'
2020-04-08 12:44:42,746 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2020-04-08 12:44:42,747 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 12:44:42,749 [DEBUG]  There is no memorised next action
2020-04-08 12:44:42,753 [DEBUG]  There is no active form
2020-04-08 12:44:42,755 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:44:42,756 [DEBUG]  Predicted next action 'find_facility_types' with confidence 0.28.
2020-04-08 12:44:42,759 [DEBUG]  Calling action endpoint to run action 'find_facility_types'.
2020-04-08 12:44:44,837 [ERROR]  Failed to run custom action 'find_facility_types'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: [WinError 10054] An existing connection was forcibly closed by the remote host
2020-04-08 12:44:44,842 [ERROR]  Encountered an exception while running action 'find_facility_types'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-08 12:44:44,849 [DEBUG]  Failed to execute custom action.
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\utils\endpoints.py", line 146, in request
    **kwargs,
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\client.py", line 504, in _request
    await resp.start(conn)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\processor.py", line 616, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 580, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
2020-04-08 12:44:44,854 [DEBUG]  Action 'find_facility_types' ended with events '[]'.
2020-04-08 12:44:44,859 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: None
	name: None
	remedy: None
	symptom: None
2020-04-08 12:44:44,873 [DEBUG]  Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_find_facility_types': 1.0, 'intent_greet': 1.0}]
2020-04-08 12:44:44,874 [DEBUG]  There is a memorised next action 'action_listen'
2020-04-08 12:44:44,886 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2020-04-08 12:44:44,890 [DEBUG]  There is no active form
2020-04-08 12:44:44,898 [DEBUG]  Predicted next action using policy_0_MemoizationPolicy
2020-04-08 12:44:44,899 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-08 12:44:44,903 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 12:44:44,910 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 12:45:06,027 [DEBUG]  Recreating tracker for id 'healthchain'
2020-04-08 12:45:06,057 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 12:45:06,061 [DEBUG]  Adding following selector key to message property: default
2020-04-08 12:45:06,065 [DEBUG]  Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.9737305641174316}' and entities '[]'
2020-04-08 12:45:06,074 [DEBUG]  Logged UserUtterance - tracker now has 7 events.
2020-04-08 12:45:06,077 [DEBUG]  Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_find_facility_types': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 12:45:06,086 [DEBUG]  There is no memorised next action
2020-04-08 12:45:06,095 [DEBUG]  There is no active form
2020-04-08 12:45:06,098 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:45:06,102 [DEBUG]  Predicted next action 'find_facility_types' with confidence 0.27.
2020-04-08 12:45:06,108 [DEBUG]  Calling action endpoint to run action 'find_facility_types'.
2020-04-08 12:45:10,176 [ERROR]  Failed to run custom action 'find_facility_types'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [Connect call failed ('127.0.0.1', 5055)]
2020-04-08 12:45:10,186 [ERROR]  Encountered an exception while running action 'find_facility_types'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-04-08 12:45:10,189 [DEBUG]  Failed to execute custom action.
Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "c:\users\asus\miniconda3\envs\rasa\lib\asyncio\base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "c:\users\asus\miniconda3\envs\rasa\lib\asyncio\base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "c:\users\asus\miniconda3\envs\rasa\lib\asyncio\selector_events.py", line 473, in sock_connect
    return await fut
  File "c:\users\asus\miniconda3\envs\rasa\lib\asyncio\selector_events.py", line 503, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 5055)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\utils\endpoints.py", line 146, in request
    **kwargs,
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\aiohttp\connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5055 ssl:default [Connect call failed ('127.0.0.1', 5055)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\processor.py", line 616, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "c:\users\asus\miniconda3\envs\rasa\lib\site-packages\rasa\core\actions\action.py", line 580, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
2020-04-08 12:45:10,200 [DEBUG]  Action 'find_facility_types' ended with events '[]'.
2020-04-08 12:45:10,203 [DEBUG]  Current slot values: 
	facility_address: None
	facility_id: None
	facility_type: None
	location: None
	name: None
	remedy: None
	symptom: None
2020-04-08 12:45:10,214 [DEBUG]  Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_find_facility_types': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_find_facility_types': 1.0, 'intent_greet': 1.0}]
2020-04-08 12:45:10,217 [DEBUG]  There is no memorised next action
2020-04-08 12:45:10,229 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2020-04-08 12:45:10,229 [DEBUG]  There is no active form
2020-04-08 12:45:10,236 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 12:45:10,243 [DEBUG]  Predicted next action 'action_listen' with confidence 0.91.
2020-04-08 12:45:10,245 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 12:45:10,250 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 13:15:43,132 [DEBUG]  Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         OPTIONS                        handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-04-08 13:15:43,138 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-08 13:15:43,142 [DEBUG]  Using the default number of Sanic workers (1).
2020-04-08 13:15:43,155 [INFO ]  Enabling coroutine debugging. Loop id 1916307890952.
2020-04-08 13:15:43,919 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmpfpj3q18n'.
2020-04-08 13:15:45,397 [DEBUG]  Loading the model ...
2020-04-08 13:15:48,046 [DEBUG]  Finished loading the model.
2020-04-08 13:15:48,046 [DEBUG]  Building tensorflow prediction graph...
2020-04-08 13:16:00,682 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-08 13:16:00,689 [DEBUG]  Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path 'C:\Users\ASUS\AppData\Local\Temp\tmpfpj3q18n\nlu' doesn't exist?
2020-04-08 13:16:00,710 [DEBUG]  Connected to InMemoryTrackerStore.
2020-04-08 13:16:00,713 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2020-04-08 13:16:01,566 [DEBUG]  Extracted model to 'C:\Users\ASUS\AppData\Local\Temp\tmphzwor07d'.
2020-04-08 13:16:01,573 [DEBUG]  Using yaml library: c:\users\asus\miniconda3\envs\rasa\lib\site-packages\ruamel\yaml\__init__.py
2020-04-08 13:16:01,702 [DEBUG]  Loading the model ...
2020-04-08 13:16:03,242 [DEBUG]  Finished loading the model.
2020-04-08 13:16:03,244 [DEBUG]  Building tensorflow prediction graph...
2020-04-08 13:16:04,760 [DEBUG]  Finished building tensorflow prediction graph.
2020-04-08 13:16:04,770 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-04-08 13:16:09,629 [DEBUG]  Creating a new tracker for id 'healthchain'.
2020-04-08 13:16:09,634 [DEBUG]  Starting a new session for conversation ID 'healthchain'.
2020-04-08 13:16:09,638 [DEBUG]  Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x000001BE360D8A08>, <rasa.core.events.ActionExecuted object at 0x000001BE34BD9548>]'.
2020-04-08 13:16:09,641 [DEBUG]  Current slot values: 
	name: None
	remedy: None
	symptom: None
2020-04-08 13:16:10,189 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 13:16:10,191 [DEBUG]  Adding following selector key to message property: default
2020-04-08 13:16:10,192 [DEBUG]  Received user message 'hey there' with intent '{'name': 'greet', 'confidence': 0.9746032953262329}' and entities '[]'
2020-04-08 13:16:10,195 [DEBUG]  Logged UserUtterance - tracker now has 4 events.
2020-04-08 13:16:10,198 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 13:16:10,201 [DEBUG]  There is a memorised next action 'utter_greet'
2020-04-08 13:16:10,206 [DEBUG]  Predicted next action using policy_0_MemoizationPolicy
2020-04-08 13:16:10,208 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2020-04-08 13:16:10,210 [DEBUG]  Action 'utter_greet' ended with events '[BotUttered('Hey there! Please choose one of the healthcare facility options:', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1586331970.2109098)]'.
2020-04-08 13:16:10,213 [DEBUG]  Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
2020-04-08 13:16:10,214 [DEBUG]  There is a memorised next action 'action_listen'
2020-04-08 13:16:10,218 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2020-04-08 13:16:10,221 [DEBUG]  Predicted next action using policy_0_MemoizationPolicy
2020-04-08 13:16:10,223 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-04-08 13:16:10,225 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 13:16:10,228 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 13:16:22,754 [DEBUG]  Recreating tracker for id 'healthchain'
2020-04-08 13:16:22,780 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 13:16:22,780 [DEBUG]  Adding following selector key to message property: default
2020-04-08 13:16:22,786 [DEBUG]  Received user message 'weather' with intent '{'name': 'ask_weather', 'confidence': 0.9983774423599243}' and entities '[]'
2020-04-08 13:16:22,793 [DEBUG]  Logged UserUtterance - tracker now has 8 events.
2020-04-08 13:16:22,796 [DEBUG]  Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_weather': 1.0}]
2020-04-08 13:16:22,796 [DEBUG]  There is no memorised next action
2020-04-08 13:16:22,812 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:22,813 [DEBUG]  Predicted next action 'utter_bye' with confidence 0.21.
2020-04-08 13:16:22,820 [DEBUG]  Action 'utter_bye' ended with events '[BotUttered('Bye, it was nice talking to you!', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1586331982.8166957)]'.
2020-04-08 13:16:22,824 [DEBUG]  Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_weather': 1.0}, {'intent_ask_weather': 1.0, 'prev_utter_bye': 1.0}]
2020-04-08 13:16:22,824 [DEBUG]  There is no memorised next action
2020-04-08 13:16:22,837 [DEBUG]  There is no mapped action for the predicted intent, 'ask_weather'.
2020-04-08 13:16:22,848 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:22,851 [DEBUG]  Predicted next action 'action_listen' with confidence 0.88.
2020-04-08 13:16:22,853 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 13:16:22,861 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 13:16:35,666 [DEBUG]  Recreating tracker for id 'healthchain'
2020-04-08 13:16:35,691 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 13:16:35,696 [DEBUG]  Adding following selector key to message property: default
2020-04-08 13:16:35,699 [DEBUG]  Received user message 'tell em a joke' with intent '{'name': 'telljoke', 'confidence': 0.9919540882110596}' and entities '[]'
2020-04-08 13:16:35,704 [DEBUG]  Logged UserUtterance - tracker now has 12 events.
2020-04-08 13:16:35,711 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_weather': 1.0}, {'intent_ask_weather': 1.0, 'prev_utter_bye': 1.0}, {'intent_telljoke': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 13:16:35,712 [DEBUG]  There is no memorised next action
2020-04-08 13:16:35,725 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:35,727 [DEBUG]  Predicted next action 'utter_greet' with confidence 0.20.
2020-04-08 13:16:35,728 [DEBUG]  Action 'utter_greet' ended with events '[BotUttered('Hey there! Please choose one of the healthcare facility options:', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1586331995.728631)]'.
2020-04-08 13:16:35,740 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_weather': 1.0}, {'intent_ask_weather': 1.0, 'prev_utter_bye': 1.0}, {'intent_telljoke': 1.0, 'prev_action_listen': 1.0}, {'intent_telljoke': 1.0, 'prev_utter_greet': 1.0}]
2020-04-08 13:16:35,742 [DEBUG]  There is no memorised next action
2020-04-08 13:16:35,757 [DEBUG]  There is no mapped action for the predicted intent, 'telljoke'.
2020-04-08 13:16:35,759 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:35,763 [DEBUG]  Predicted next action 'action_listen' with confidence 0.87.
2020-04-08 13:16:35,766 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 13:16:35,776 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 13:16:43,029 [DEBUG]  Recreating tracker for id 'healthchain'
2020-04-08 13:16:43,046 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 13:16:43,046 [DEBUG]  Adding following selector key to message property: default
2020-04-08 13:16:43,050 [DEBUG]  Received user message 'what can u do' with intent '{'name': 'ask_howdoing', 'confidence': 0.1888991743326187}' and entities '[]'
2020-04-08 13:16:43,055 [DEBUG]  Logged UserUtterance - tracker now has 16 events.
2020-04-08 13:16:43,057 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_ask_weather': 1.0}, {'intent_ask_weather': 1.0, 'prev_utter_bye': 1.0}, {'intent_telljoke': 1.0, 'prev_action_listen': 1.0}, {'intent_telljoke': 1.0, 'prev_utter_greet': 1.0}, {'intent_ask_howdoing': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 13:16:43,059 [DEBUG]  There is no memorised next action
2020-04-08 13:16:43,067 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:43,071 [DEBUG]  Predicted next action 'utter_greet' with confidence 0.22.
2020-04-08 13:16:43,074 [DEBUG]  Action 'utter_greet' ended with events '[BotUttered('Hi. What are you looking for?', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1586332003.0735998)]'.
2020-04-08 13:16:43,077 [DEBUG]  Current tracker state [{'intent_ask_weather': 1.0, 'prev_utter_bye': 1.0}, {'intent_telljoke': 1.0, 'prev_action_listen': 1.0}, {'intent_telljoke': 1.0, 'prev_utter_greet': 1.0}, {'intent_ask_howdoing': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_ask_howdoing': 1.0}]
2020-04-08 13:16:43,077 [DEBUG]  There is no memorised next action
2020-04-08 13:16:43,092 [DEBUG]  There is no mapped action for the predicted intent, 'ask_howdoing'.
2020-04-08 13:16:43,092 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:43,096 [DEBUG]  Predicted next action 'action_listen' with confidence 0.86.
2020-04-08 13:16:43,100 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 13:16:43,103 [DEBUG]  Deleted lock for conversation 'healthchain'.
2020-04-08 13:16:52,008 [DEBUG]  Recreating tracker for id 'healthchain'
2020-04-08 13:16:52,035 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2020-04-08 13:16:52,039 [DEBUG]  Adding following selector key to message property: default
2020-04-08 13:16:52,043 [DEBUG]  Received user message 'jokes' with intent '{'name': 'telljoke', 'confidence': 0.9962559342384338}' and entities '[]'
2020-04-08 13:16:52,048 [DEBUG]  Logged UserUtterance - tracker now has 20 events.
2020-04-08 13:16:52,054 [DEBUG]  Current tracker state [{'intent_telljoke': 1.0, 'prev_action_listen': 1.0}, {'intent_telljoke': 1.0, 'prev_utter_greet': 1.0}, {'intent_ask_howdoing': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_ask_howdoing': 1.0}, {'intent_telljoke': 1.0, 'prev_action_listen': 1.0}]
2020-04-08 13:16:52,057 [DEBUG]  There is no memorised next action
2020-04-08 13:16:52,066 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:52,070 [DEBUG]  Predicted next action 'utter_greet' with confidence 0.16.
2020-04-08 13:16:52,075 [DEBUG]  Action 'utter_greet' ended with events '[BotUttered('Hey there! Please choose one of the healthcare facility options:', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {}, 1586332012.0755491)]'.
2020-04-08 13:16:52,082 [DEBUG]  Current tracker state [{'intent_telljoke': 1.0, 'prev_utter_greet': 1.0}, {'intent_ask_howdoing': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_ask_howdoing': 1.0}, {'intent_telljoke': 1.0, 'prev_action_listen': 1.0}, {'intent_telljoke': 1.0, 'prev_utter_greet': 1.0}]
2020-04-08 13:16:52,082 [DEBUG]  There is no memorised next action
2020-04-08 13:16:52,096 [DEBUG]  There is no mapped action for the predicted intent, 'telljoke'.
2020-04-08 13:16:52,099 [DEBUG]  Predicted next action using policy_1_TEDPolicy
2020-04-08 13:16:52,101 [DEBUG]  Predicted next action 'action_listen' with confidence 0.85.
2020-04-08 13:16:52,104 [DEBUG]  Action 'action_listen' ended with events '[]'.
2020-04-08 13:16:52,111 [DEBUG]  Deleted lock for conversation 'healthchain'.
